/* BEGIN */
export const GET_ALL_CATEGORIES_BEGIN = "GET_ALL_CATEGORIES_BEGIN";
/* SUCCESS */
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
/* FAILURE */
export const GET_ALL_CATEGORIES_FAILURE = "GET_ALL_CATEGORIES_FAILURE";
