// GET ALL POSTS BEGIN
export const GET_ALL_POSTS_BEGIN = "GET_ALL_POSTS_BEGIN";
// GET ALL POSTS SUCCESS
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
// GET ALL POSTS BEGIN
export const GET_ALL_POSTS_FAILURE = "GET_ALL_POSTS_FAILURE";
// SEARCH POSTS BEGIN
export const SEARCH_POSTS_BEGIN = "SEARCH_POSTS_BEGIN";
// SEARCH POSTS SUCCESS
export const SEARCH_POSTS_SUCCESS = "SEARCH_POSTS_SUCCESS";
// SEARCH POSTS FAILURE
export const SEARCH_POSTS_FAILURE = "SEARCH_POSTS_FAILURE";
