// GET ALL POSTS BEGIN
export const GET_ALL_POSTS_BEGIN = "GET_ALL_POSTS_BEGIN";
// GET ALL POSTS SUCCESS
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
// GET ALL POSTS BEGIN
export const GET_ALL_POSTS_FAILURE = "GET_ALL_POSTS_FAILURE";
